name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Win64-Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get install libevent-dev libboost-all-dev -y
    - name: Test run github actions
      run: ./autogen.sh; ./configure --without-gui --disable-wallet
