name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autogen
      run: ./autogen.sh
    - name: Configure project
      run: ./configure
    - name: Run make
      run: echo "Proc:" $(nproc); make -j$(nproc)
