name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-Win64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test run github actions
      run: ./.github/compile-win64.sh
