name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get install libevent-dev libboost-all-dev -y
    - name: Autogen & Configure
      run: ./autogen.sh; ./configure --without-gui --disable-wallet
    - name: Make
      run: make -j$(nproc)
